name: Unzip pg and add pg

on:
  #push:
  schedule:
    - cron: 15,45 0-18,22-23 * * *
  workflow_dispatch:
    inputs:
      rebuild:
        description: '忽略构建记录以重新构建'
        required: false
        type: boolean
  
jobs:

  run-python-script: 

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v1
       
     - name: Set up Python 3.9
       uses: actions/setup-python@v5
       with:
        python-version: 3.9 # 可以根据需要更改 Python 版本
     
     - name: telethon download telegram channel zip
       run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py
     
     - name: Unzip file
       run: |
         if [ "./files/PandaGroovePG/*.zip" == "./*.zip" ]; then
          echo "相同."
          exit 0 # 跳过后续步骤
         else
         echo "不相同继续."
          unzip -o files/PandaGroovePG/*.zip -d pg
         fi
     - name: Add unzipped files pg to xytv
       run: |
          git clone https://github.com/xinyi1984/xytv 
          rm -r xytv/js/*
          rm -r xytv/lib/*
          rm -r xytv/pg.jar
          rm -r xytv/jsm.json
          rm -r xytv/pg.jar.md5
          rm -r xytv/README.txt
          rm -r xytv/*.zip
          mv ./pg/* xytv
          co ./files/PandaGroovePG/*.zip xytv
          sed -i "s#https://fm.t4tv.hz.cz/json/market.json#https://mirror.ghproxy.com/https://raw.githubusercontent.com/xinyi1984/xytv/master/json/market.json#g" xytv/jsm.json
          sed -i "s#lib/alishare.txt#alishare.txt#g" xytv/jsm.json
          cd xytv
          if git diff --quiet; then
            echo "没有未提交的更改。"
          else
            echo "存在未提交的更改。"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add --all
            git remote rm origin
            git remote add origin "https://xytv:${{ secrets.GITHUBXYTV_TOKEN }}@github.com/xinyi1984/xytv"
            git commit -m "更新JSM Add unzipped files to xytv"
            git push -f -u origin master
          fi
       continue-on-error: true
     - name: Commit and push changes
       run: |
        rm -r ./*.zip
        mv ./files/PandaGroovePG/*.zip .
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add zip files"
     - name: Push changes to remote repository
       uses: ad-m/github-push-action@master
       with:
          github_token: ${{ secrets.GITHUBXYTV_TOKEN }}
          branch: main
