name: Unzip pg and add pg

on:
  #push:
  schedule:
    - cron: 15,45 0-18,22-23 * * *
  workflow_dispatch:
    inputs:
      rebuild:
        description: '忽略构建记录以重新构建'
        required: false
        type: boolean
  
jobs:

  run-python-script: 

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
         fetch-depth: 0 # 获取所有历史记录，以便搜索ZIP文件
          
     - name: Set up Python 3.9
       uses: actions/setup-python@v5
       with:
        python-version: 3.9 # 可以根据需要更改 Python 版本
        
     - name: telethon download telegram channel zip
       run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py
        
     - name: Get downloaded ZIP filename
       id: get-downloaded-zip
       run: |
          # 假设下载的ZIP文件是唯一的，你可以使用ls命令来获取文件名
          DOWNLOADED_ZIP=$(ls ./files/PandaGroovePG/*.zip)
          # 检查是否找到了ZIP文件
          if [[ -n "$DOWNLOADED_ZIP" ]]; then
            # 提取ZIP文件名（不包含路径）
            DOWNLOADED_ZIP_NAME=$(basename "$DOWNLOADED_ZIP")
            echo "::set-output name=zip-name::$DOWNLOADED_ZIP_NAME"
          else
            echo "没有找到下载的ZIP文件。"
            exit 0
          fi

     - name: List ZIP files in repository
       id: list-repo-zip-files
       run: |
          # Git命令不会直接列出文件，但你可以通过一些技巧来检查仓库中是否有匹配的ZIP文件
          # 例如，你可以使用git ls-tree命令来获取特定提交的目录列表
          # 这里假设你知道要比较的提交的SHA值，或者你可以使用HEAD来表示最新的提交
          ZIP_FILES=$(git ls-tree -r --name-only HEAD | grep '\.zip$')

          # 检查是否找到了ZIP文件
          if [[ -n "$ZIP_FILES" ]]; then
            # 假设我们只对第一个ZIP文件名感兴趣，或者你可以添加逻辑来处理多个文件名
            REPO_ZIP_NAME=$(echo "$ZIP_FILES" | head -n 1)
            echo "::set-output name=repo-zip-name::$REPO_ZIP_NAME"
          else
            echo "仓库中没有找到ZIP文件。"
            exit 0
          fi

     - name: Compare filenames and decide to skip work
       id: compare-and-skip
       run: |
          DOWNLOADED_ZIP_NAME=${{ steps.get-downloaded-zip.outputs.zip-name }}
          REPO_ZIP_NAME=${{ steps.list-repo-zip-files.outputs.repo-zip-name }}

          # 比较文件名
          if [[ "$DOWNLOADED_ZIP_NAME" == "$REPO_ZIP_NAME" ]]; then
            echo "ZIP 文件名相同，跳过后续工作。"
            exit 0
          else
            echo "ZIP 文件名不同，继续执行后续工作。"
            # 设置一个输出变量，以便在后续步骤中判断是否应该执行工作
            echo "::set-output name=skip-work::false"
          fi
      
     - name: Unzip file
       if: ${{ !steps.compare-and-skip.outputs.skip-work }}
       run: |
          unzip -o files/PandaGroovePG/*.zip -d pg
     - name: Add unzipped files pg to xytv
       if: ${{ !steps.compare-and-skip.outputs.skip-work }}
       run: |
          git clone https://github.com/xinyi1984/xytv 
          rm -r xytv/js/*
          rm -r xytv/lib/*
          rm -r xytv/pg.jar
          rm -r xytv/jsm.json
          rm -r xytv/pg.jar.md5
          rm -r xytv/README.txt
          rm -r xytv/*.zip
          mv ./pg/* xytv
          cp ./files/PandaGroovePG/*.zip xytv
          sed -i "s#https://fm.t4tv.hz.cz/json/market.json#https://mirror.ghproxy.com/https://raw.githubusercontent.com/xinyi1984/xytv/master/json/market.json#g" xytv/jsm.json
          sed -i "s#lib/alishare.txt#alishare.txt#g" xytv/jsm.json
          cd xytv
          if git diff --quiet; then
            echo "没有未提交的更改。"
          else
            echo "存在未提交的更改。"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add --all
            git remote rm origin
            git remote add origin "https://xytv:${{ secrets.GITHUBXYTV_TOKEN }}@github.com/xinyi1984/xytv"
            git commit -m "更新JSM Add unzipped files to xytv"
            git push -f -u origin master
          fi
       continue-on-error: true
     - name: Commit and push changes
       if: ${{ !steps.compare-and-skip.outputs.skip-work }}
       run: |
        rm -r ./*.zip
        mv ./files/PandaGroovePG/*.zip .
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add zip files"
     - name: Push changes to remote repository
       if: ${{ !steps.compare-and-skip.outputs.skip-work }}
       uses: ad-m/github-push-action@master
       with:
          github_token: ${{ secrets.GITHUBXYTV_TOKEN }}
          branch: main
