name: Unzip pg and add pg

on:
  #push:
  schedule:
    - cron: 15,45 0-18,22-23 * * *
  workflow_dispatch:
    inputs:
      rebuild:
        description: '忽略构建记录以重新构建'
        required: false
        type: boolean
  
jobs:

  run-python-script: 

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
         fetch-depth: 0 # 获取所有历史记录，以便搜索ZIP文件
          
     - name: Set up Python 3.9
       uses: actions/setup-python@v5
       with:
        python-version: 3.9 # 可以根据需要更改 Python 版本
        
     - name: telethon download telegram channel zip
       run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py
        
     # 假设下载的 ZIP 文件现在位于 ./files/PandaGroovePG/ 目录下
     - name: Get downloaded ZIP filename
       id: get-downloaded-zip
       run: |
          # 列出 ./files/PandaGroovePG/ 目录下的 ZIP 文件
          DOWNLOADED_ZIP=$(ls ./files/PandaGroovePG/*.zip)

          # 检查是否找到了 ZIP 文件
          if [[ -n "$DOWNLOADED_ZIP" ]]; then
            # 提取 ZIP 文件名（不包含路径）
            DOWNLOADED_ZIP_NAME=$(basename "$DOWNLOADED_ZIP")
            echo "::set-output name=zip-name::$DOWNLOADED_ZIP_NAME"
          else
            echo "没有找到下载的 ZIP 文件。"
            exit 1
          fi

     - name: List ZIP files in repository
       id: list-repo-zip-files
       run: |
          # 列出仓库根目录下的 ZIP 文件
          cd telegram-channel-zip-downloader
          REPO_ZIP_FILES=$(ls *.zip)

          # 如果没有找到 ZIP 文件，则直接退出
          if [[ -z "$REPO_ZIP_FILES" ]]; then
            echo "仓库中没有找到 ZIP 文件。"
            exit 0
          fi

          # 假设我们只对第一个 ZIP 文件感兴趣，或者你知道要比较的具体文件名
          REPO_ZIP_NAME=$(basename "$REPO_ZIP_FILES")
          echo "::set-output name=repo-zip-name::$REPO_ZIP_NAME"

     - name: Compare filenames and decide to skip work
       id: compare-and-skip
       run: |
          DOWNLOADED_ZIP_NAME=${{ steps.get-downloaded-zip.outputs.zip-name }}
          REPO_ZIP_NAME=${{ steps.list-repo-zip-files.outputs.repo-zip-name }}

          # 比较文件名
          if [[ "$DOWNLOADED_ZIP_NAME" == "$REPO_ZIP_NAME" ]]; then
            echo "ZIP 文件名相同，跳过后续工作。"
            exit 0
          else
            echo "ZIP 文件名不同，继续执行后续工作。"
          fi

      # 后续步骤
      
     - name: Unzip file
       if: ${{ !success() }}
       run: |
          unzip -o files/PandaGroovePG/*.zip -d pg
     - name: Add unzipped files pg to xytv
       run: |
          git clone https://github.com/xinyi1984/xytv 
          rm -r xytv/js/*
          rm -r xytv/lib/*
          rm -r xytv/pg.jar
          rm -r xytv/jsm.json
          rm -r xytv/pg.jar.md5
          rm -r xytv/README.txt
          rm -r xytv/*.zip
          mv ./pg/* xytv
          cp ./files/PandaGroovePG/*.zip xytv
          sed -i "s#https://fm.t4tv.hz.cz/json/market.json#https://mirror.ghproxy.com/https://raw.githubusercontent.com/xinyi1984/xytv/master/json/market.json#g" xytv/jsm.json
          sed -i "s#lib/alishare.txt#alishare.txt#g" xytv/jsm.json
          cd xytv
          if git diff --quiet; then
            echo "没有未提交的更改。"
          else
            echo "存在未提交的更改。"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add --all
            git remote rm origin
            git remote add origin "https://xytv:${{ secrets.GITHUBXYTV_TOKEN }}@github.com/xinyi1984/xytv"
            git commit -m "更新JSM Add unzipped files to xytv"
            git push -f -u origin master
          fi
       continue-on-error: true
     - name: Commit and push changes
       if: ${{ !success() }}
       run: |
        rm -r .*.zip
        mv ./files/PandaGroovePG/*.zip .
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add zip files"
     - name: Push changes to remote repository
       if: ${{ !success() }}
       uses: ad-m/github-push-action@master
       with:
          github_token: ${{ secrets.GITHUBXYTV_TOKEN }}
          branch: main
