name: Unzip pg and add pg

on:
  push:
  schedule:
    - cron: 15,45 0-18,22-23 * * *
  workflow_dispatch:
  
jobs:

  run-python-script:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v1
     
     - name: Check New Commit
       run: |
          upStream=https://github.com/xinyi1984/xytv
          echo "upStream=$upStream" >> $GITHUB_ENV
          commit=$(curl -sL $upStream/commits/master|grep -o "/xinyi1984/xytv/commit/[a-z0-9]\+" |head -1 | cut -d\/ -f5)
          if ! grep -q "$commit" README.md || [ "${{ inputs.rebuild }}" == "true" ]; then
            echo "commit=$commit" >> $GITHUB_ENV
            echo "commitS=${commit:0:7}" >> $GITHUB_ENV
          fi
     
     - name: Set up Python 3.9
       if: ${{ env.commit }}
       uses: actions/setup-python@v5
       with:
        python-version: 3.9
     
     - name: telethon download telegram channel zip
       if: ${{ env.commit }}
       run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py
     
     - name: Release Note
       if: ${{ env.commit }}
        working-directory: telegram-channel-zip-downloader
        run: |
          lastCommit=$(grep "xinyi1984\/xytv\/tree\/master" ${{ github.workspace }}/README.md |grep -o '[a-z0-9]\{40\}')
          export LESSCHARSET=utf-8
          echo -e "Credit: [xinyi1984/xytv/master](${{ env.upStream }})\nCommit: ${{ env.commit }}\nChangelog:" > apk/xinyi1984-Release.log
          if [ "${{ env.commit }}" == "${lastCommit}" ]; then
            git log --pretty=format:%B ${{ env.commitS }} -1 |sed -e "s# \{2,\}#\n#g" -e "/^Merge \(pull\|branch\|remote\)/d" -e '/^$/d' |cat -n |sort -k2,2 -k1,1n |uniq -f1 |sort -k1,1n |cut -f2- >> apk/${{ matrix.userName }}-Release.log
          else
            git log --pretty=format:%B ${{ env.commitS }}...${lastCommit:0:7} |sed -e "s# \{2,\}#\n#g" -e "/^Merge \(pull\|branch\|remote\)/d" -e '/^$/d' |cat -n |sort -k2,2 -k1,1n |uniq -f1 |sort -k1,1n |cut -f2- >> apk/${{ matrix.userName }}-Release.log
          fi   
     
     - name: Upload artifact
       if: ${{ env.commit }}
       uses: actions/upload-artifact@v4
       with:
          name: pg
          path: files/PandaGroovePG
     
     - name: Unzip file
       if: ${{ env.commit }}
       run: |
         unzip -o files/PandaGroovePG/*.zip -d pg

     - name: Add unzipped files pg to xytv
       if: ${{ env.commit }}
       run: |
          git clone https://github.com/xinyi1984/xytv
          sed -i "s#https://fm.t4tv.hz.cz/json/market.json#https://mirror.ghproxy.com/https://raw.githubusercontent.com/xinyi1984/xytv/master/json/market.json#g" xytv/jsm.json
          sed -i "s#lib/alishare.txt#alishare.txt#g" xytv/jsm.json
          mv ./files/PandaGroovePG/*.zip xytv
          cd xytv
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git remote rm origin
          git remote add origin "https://xytv:${{ secrets.GITHUBXYTV_TOKEN }}@github.com/xinyi1984/xytv"
          git commit -m "更新JSM Add unzipped files to xytv"
          git push -f -u origin master
       continue-on-error: true
