name: Unzip zx and add zx

on:
  #push:
  schedule:
    - cron: '0 */8 * * *'
# 这里默认24小时内执行3次
  workflow_dispatch:
  
jobs:

  run-python-script: 

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         fetch-depth: 0 # 获取所有历史记录，以便搜索ZIP文件
          
     - name: Set up Python 3.9
       uses: actions/setup-python@v5
       with:
        python-version: 3.9 # 可以根据需要更改 Python 版本
        
     - name: telethon download telegram channel zip
       env:
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
       run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python zx.py
        
     - name: Get the name of the downloaded ZIP file
       id: get-zip-name
       run: |
         set -euo pipefail
         export LC_ALL=en_US.UTF-8
         DOWNLOAD_DIR="./files/juejijianghu"
    
         # 检查 ZIP 文件数量（严格模式）
         shopt -s nullglob
         zip_files=("$DOWNLOAD_DIR"/*.zip)
         if (( ${#zip_files[@]} == 0 )); then
           echo "::error::未找到 ZIP 文件: $DOWNLOAD_DIR"
           exit 1
         elif (( ${#zip_files[@]} > 1 )); then
           echo "::error::发现多个 ZIP 文件: ${zip_files[*]}"
           exit 1
         fi

         echo "DOWNLOADED_ZIP_NAME=${zip_files[0]}" >> $GITHUB_ENV
         echo "成功获取 ZIP 文件: ${zip_files[0]##*/}"

     - name: List ZIP files in the repository
       id: list-zip-files
       run: |
         set -euo pipefail
         export LC_ALL=en_US.UTF-8
    
         # 使用 Git 原生命令快速获取 ZIP 列表
         if ! git ls-tree -r --name-only HEAD | grep -q '\.zip$'; then
           echo "ZIP_FILES=" >> $GITHUB_ENV
           echo "::warning::仓库中未找到 ZIP 文件"
           exit 0
         fi
    
         zip_files=$(git ls-tree -r --name-only HEAD | grep '\.zip$' | awk '{printf "• %s\n", $0}')
         echo "ZIP_FILES=${zip_files//$'\n'/%0A}" >> $GITHUB_ENV  # 处理多行输出
         echo "仓库 ZIP 文件列表:"
         echo "$zip_files"

     - name: Check filename match
       id: check-match
       run: |
         set -euo pipefail
         export LC_ALL=en_US.UTF-8
    
         # 使用 basename 规范化文件名比较
         repo_files=$(sed 's/%0A/\n/g' <<< "${ZIP_FILES//• /}")  # 解码多行内容
         downloaded_name=$(basename "$DOWNLOADED_ZIP_NAME")
    
         if grep -qF "$downloaded_name" <<< "$repo_files"; then
           echo "::notice::文件已存在: $downloaded_name"
           echo "ZIP_MATCH=true" >> $GITHUB_ENV
         else
           echo "::notice::新文件: $downloaded_name"
           echo "ZIP_MATCH=false" >> $GITHUB_ENV
         fi
      
     - name: Unzip file
       if: env.ZIP_MATCH == 'false'
       run: |
          unzip -o files/juejijianghu/*.zip -d zx
         
     - name: Add unzipped files zx to zx
       if: env.ZIP_MATCH == 'false'
       run: |
          git clone --depth 5 --branch zx https://github.com/xinyi1984/xytv.git 
          rm -r xytv/json/*
          rm -r xytv/lib/*
          rm -r xytv/custom_spider.jar
          rm -r xytv/FongMi.json
          rm -r xytv/readme-tg.txt
          rm -r xytv/readme.txt
          rm -r xytv/*.zip
          mv ./zx/* xytv
          cp ./files/juejijianghu/*.zip xytv
          sed -i "s#\"sites\": \[#\"sites\": [{\"key\": \"应用商店\",\"name\": \"应用商店\",\"type\": 3,\"api\": \"csp_Market\",\"searchable\": 0,\"changeable\": 0,\"ext\": \"https://ghfast.top/https://raw.githubusercontent.com/xinyi1984/xytv/master/json/market.json\",\"jar\": \"https://ghfast.top/https://raw.githubusercontent.com/FongMi/CatVodSpider/main/jar/custom_spider.jar\"},#g" xytv/FongMi.json
          cd xytv
          if git diff --quiet; then
            echo "没有未提交的更改。"
          else
            echo "存在未提交的更改。"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add --all
            git remote rm origin
            git remote add origin "https://xytv:${{ secrets.GITHUBXYTV_TOKEN }}@github.com/xinyi1984/xytv"
            git commit -m "更新FongMi Add unzipped files to xytv"
            git push -f -u origin zx
          fi
       continue-on-error: true
       
     - name: Upload zip To telegram-channel-zip-downloader
       if: env.ZIP_MATCH == 'false'
       run: |  
          rm -rf  xytv
          rm -r ./真心*.zip
          rm -r ./zx
          mv ./files/juejijianghu/*.zip .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "更新zip"
          git push -f -u origin main
