name: Unzip pg and add pg

on:
  #push:
  schedule:
    - cron: 15,45 0-18,22-23 * * *
  workflow_dispatch:
    inputs:
      rebuild:
        description: '忽略构建记录以重新构建'
        required: false
        type: boolean
  
jobs:

  run-python-script: 

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v3
       
     - name: Set up Python 3.9
       uses: actions/setup-python@v5
       with:
        python-version: 3.9 # 可以根据需要更改 Python 版本
     
     - name: telethon download telegram channel zip
       run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py
        
     - name: Get SHA256 hash of downloaded ZIP
       id: downloaded-zip-hash
       run: |
          echo "::set-output name=hash::$(sha256sum /files/PandaGroovePG/*.zip | awk '{print $1}')"

     - name: Get SHA256 hash of repository ZIP
       id: repository-zip-hash
       shell: bash
       run: |
          REPOSITORY_ZIP="/pg/*.zip" # Replace with the name of the ZIP file in your repository
          if [[ -f "$REPOSITORY_ZIP" ]]; then
            echo "::set-output name=hash::$(sha256sum "$REPOSITORY_ZIP" | awk '{print $1}')"
          else
            echo "ZIP file does not exist in the repository."
            exit 1
          fi

     - name: Compare hashes and skip steps if identical
       if: steps.downloaded-zip-hash.outputs.hash == steps.repository-zip-hash.outputs.hash
       run: |
          echo "ZIP files are identical, skipping further steps."
          
     - name: Unzip file
       run: |
          unzip -o files/PandaGroovePG/*.zip -d pg
     - name: Add unzipped files pg to xytv
       run: |
          git clone https://github.com/xinyi1984/xytv 
          rm -r xytv/js/*
          rm -r xytv/lib/*
          rm -r xytv/pg.jar
          rm -r xytv/jsm.json
          rm -r xytv/pg.jar.md5
          rm -r xytv/README.txt
          rm -r xytv/*.zip
          mv ./pg/* xytv
          cp ./files/PandaGroovePG/*.zip xytv
          sed -i "s#https://fm.t4tv.hz.cz/json/market.json#https://mirror.ghproxy.com/https://raw.githubusercontent.com/xinyi1984/xytv/master/json/market.json#g" xytv/jsm.json
          sed -i "s#lib/alishare.txt#alishare.txt#g" xytv/jsm.json
          cd xytv
          if git diff --quiet; then
            echo "没有未提交的更改。"
          else
            echo "存在未提交的更改。"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add --all
            git remote rm origin
            git remote add origin "https://xytv:${{ secrets.GITHUBXYTV_TOKEN }}@github.com/xinyi1984/xytv"
            git commit -m "更新JSM Add unzipped files to xytv"
            git push -f -u origin master
          fi
       continue-on-error: true
     - name: Commit and push changes
       run: |
        rm -r ./pg*.zip
        mv ./files/PandaGroovePG/*.zip ./pg
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add zip files"
     - name: Push changes to remote repository
       uses: ad-m/github-push-action@master
       with:
          github_token: ${{ secrets.GITHUBXYTV_TOKEN }}
          branch: main
