name: Unzip pg and add pg

on:
  #push:
  schedule:
    - cron: 15,45 0-18,22-23 * * *
  workflow_dispatch:
    inputs:
      rebuild:
        description: '忽略构建记录以重新构建'
        required: false
        type: boolean
  
jobs:

  run-python-script: 

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
         fetch-depth: 0 # 获取所有历史记录，以便搜索ZIP文件
          
     - name: Set up Python 3.9
       uses: actions/setup-python@v5
       with:
        python-version: 3.9 # 可以根据需要更改 Python 版本
        
     - name: telethon download telegram channel zip
       run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py
        
     - name: Find ZIP files in downloaded directory
       id: find-downloaded-zip
       run: |
          # 查找下载的ZIP文件
          DOWNLOADED_ZIP=$(ls ./files/PandaGroovePG/*.zip 2>/dev/null)
          if [[ -n "$DOWNLOADED_ZIP" ]]; then
            echo "::set-output name=downloaded-zip::${DOWNLOADED_ZIP##*/}" # 提取文件名
          else
            echo "没有找到下载的ZIP文件。"
            exit 1
          fi

     - name: Find ZIP files in repository
       id: find-repo-zip
       run: |
          # 查找仓库中的ZIP文件
          REPO_ZIP=$(find . -type f -name ".*.zip" | head -n 1) # 假设只有一个ZIP文件，或者取第一个作为比较对象
          if [[ -n "$REPO_ZIP" ]]; then
            echo "::set-output name=repo-zip::${REPO_ZIP##*/}" # 提取文件名
          else
            echo "仓库中没有找到ZIP文件。"
            exit 1
          fi

     - name: Compare filenames and skip work if they are the same
       id: compare-filenames
       run: |
          DOWNLOADED_ZIP_NAME=${{ steps.find-downloaded-zip.outputs.downloaded-zip }}
          REPO_ZIP_NAME=${{ steps.find-repo-zip.outputs.repo-zip }}

          # 比较文件名
          if [[ "$DOWNLOADED_ZIP_NAME" == "$REPO_ZIP_NAME" ]]; then
            echo "ZIP文件名相同，跳过后续工作。"
            exit 0
          else
            echo "ZIP文件名不同，继续执行后续工作。"
          fi

      # 使用 if 条件判断来决定是否执行这个步骤
      
     - name: Unzip file
       if: ${{ steps.compare-filenames.outcome != 'success' }}
       run: |
          unzip -o files/PandaGroovePG/*.zip -d pg
     - name: Add unzipped files pg to xytv
       run: |
          git clone https://github.com/xinyi1984/xytv 
          rm -r xytv/js/*
          rm -r xytv/lib/*
          rm -r xytv/pg.jar
          rm -r xytv/jsm.json
          rm -r xytv/pg.jar.md5
          rm -r xytv/README.txt
          rm -r xytv/*.zip
          mv ./pg/* xytv
          cp ./files/PandaGroovePG/*.zip xytv
          sed -i "s#https://fm.t4tv.hz.cz/json/market.json#https://mirror.ghproxy.com/https://raw.githubusercontent.com/xinyi1984/xytv/master/json/market.json#g" xytv/jsm.json
          sed -i "s#lib/alishare.txt#alishare.txt#g" xytv/jsm.json
          cd xytv
          if git diff --quiet; then
            echo "没有未提交的更改。"
          else
            echo "存在未提交的更改。"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add --all
            git remote rm origin
            git remote add origin "https://xytv:${{ secrets.GITHUBXYTV_TOKEN }}@github.com/xinyi1984/xytv"
            git commit -m "更新JSM Add unzipped files to xytv"
            git push -f -u origin master
          fi
       continue-on-error: true
     - name: Commit and push changes
       if: ${{ steps.compare-filenames.outcome != 'success' }}
       run: |
        rm -r .*.zip
        mv ./files/PandaGroovePG/*.zip .
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add zip files"
     - name: Push changes to remote repository
       if: ${{ steps.compare-filenames.outcome != 'success' }}
       uses: ad-m/github-push-action@master
       with:
          github_token: ${{ secrets.GITHUBXYTV_TOKEN }}
          branch: main
