name: Unzip pg and add pg

on:
  #push:
  schedule:
    - cron: 15,45 0-18,22-23 * * *
  workflow_dispatch:
    inputs:
      rebuild:
        description: '忽略构建记录以重新构建'
        required: false
        type: boolean
  
jobs:

  run-python-script: 

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         fetch-depth: 0 # 获取所有历史记录，以便搜索ZIP文件
          
     - name: Set up Python 3.9
       uses: actions/setup-python@v5
       with:
        python-version: 3.9 # 可以根据需要更改 Python 版本
        
     - name: telethon download telegram channel zip
       run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py
        
     - name: Get the name of the downloaded ZIP file
       id: get-zip-name
       run: |
          # 获取下载的ZIP文件名
          downloaded_zip_name=$(ls ./files/PandaGroovePG/*.zip | head -n 1)
          echo "DOWNLOADED_ZIP_NAME=$downloaded_zip_name" >> $GITHUB_ENV

     - name: List ZIP files in the repository
       id: list-zip-files
       run: |
          # 列出仓库中的所有ZIP文件
          zip_files=$(git ls-tree -r --name-only HEAD | grep '\.zip$')
          echo "ZIP_FILES=$zip_files" >> $GITHUB_ENV

     - name: Check if downloaded ZIP filename matches a file in the repository
       id: check-match
       run: |
          # 检查下载的ZIP文件名是否与仓库中的ZIP文件名匹配
          downloaded_zip_name="${DOWNLOADED_ZIP_NAME##*/}"
          zip_files="${ZIP_FILES//'%'/'\\%'}"  # 替换%字符，避免shell解释
          if echo "$zip_files" | grep -qF -- "$downloaded_zip_name"; then
            echo "ZIP filename matches a file in the repository."
            echo "ZIP_MATCH=true" >> $GITHUB_ENV
          else
            echo "ZIP filename does not match any file in the repository."
            echo "ZIP_MATCH=false" >> $GITHUB_ENV
          fi
      
     - name: Unzip file
       if: env.ZIP_MATCH == 'false'
       run: |
          unzip -o files/PandaGroovePG/*.zip -d pg
     - name: Add unzipped files pg to xytv
       if: env.ZIP_MATCH == 'false'
       run: |
          git clone https://github.com/xinyi1984/xytv 
          rm -r xytv/js/*
          rm -r xytv/lib/*
          rm -r xytv/pg.jar
          rm -r xytv/jsm.json
          rm -r xytv/pg.jar.md5
          rm -r xytv/README.txt
          rm -r xytv/*.zip
          mv ./pg/* xytv
          cp ./files/PandaGroovePG/*.zip xytv
          sed -i "s#https://fm.t4tv.hz.cz/json/market.json#https://mirror.ghproxy.com/https://raw.githubusercontent.com/xinyi1984/xytv/master/json/market.json#g" xytv/jsm.json
          sed -i "s#lib/alishare.txt#alishare.txt#g" xytv/jsm.json
          cd xytv
          if git diff --quiet; then
            echo "没有未提交的更改。"
          else
            echo "存在未提交的更改。"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add --all
            git remote rm origin
            git remote add origin "https://xytv:${{ secrets.GITHUBXYTV_TOKEN }}@github.com/xinyi1984/xytv"
            git commit -m "更新JSM Add unzipped files to xytv"
            git push -f -u origin master
          fi
       continue-on-error: true
     - name: Commit and push changes
       if: env.ZIP_MATCH == 'false'
       run: |
        rm -r ./*.zip
        mv ./files/PandaGroovePG/*.zip .
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add zip files"
     - name: Push changes to remote repository
       if: env.ZIP_MATCH == 'false'
       uses: ad-m/github-push-action@master
       with:
          github_token: ${{ secrets.GITHUBXYTV_TOKEN }}
          branch: main
